import { PromptList } from './index';

export const florida: PromptList = [
  {
    prompt: 'NAKED FLORIDA MAN THROWS ROCKS AT CARS',
    id: 0,
  },
  {
    prompt: "FLORIDA MAN SETS HOSPITAL BED ON FIRE TO GET NURSE'S ATTENTION",
    id: 1,
  },
  {
    prompt:
      'SHOPLIFTING FLORIDA MAN FLEES STORE, STRIPS NAKED AS STEAKS FALL OUT OF HIS PANTS',
    id: 2,
  },
  {
    prompt: "FLORIDA MAN BREAKS INTO HOME, SUCKS ON SLEEPING MAN'S TOES",
    id: 3,
  },
  {
    prompt:
      'NEARLY NAKED FLORIDA MAN BREAKS INTO SCHOOL, SMEARS FECES AND CAKE FROSTING EVERYWHERE',
    id: 4,
  },
  {
    prompt:
      'WAL-MART EVACUATED AFTER FLORIDA MAN FOUND CRAWLING THROUGH CEILING',
    id: 5,
  },
  {
    prompt: '380-POUND FLORIDA MAN HIDES METH IN BELLY BUTTON',
    id: 6,
  },
  {
    prompt:
      'FLORIDA MAN TELLS POLICE BAG OF COCAINE FOUND IN CAR MUST HAVE BLOWN IN FROM THE WIND',
    id: 7,
  },
  {
    prompt:
      "FLORIDA MAN FOUND SITTING ON FAMILIES' ROOF IN HIS UNDERWEAR, HAS NO IDEA HOW HE GOT THERE",
    id: 8,
  },
  {
    prompt: "FLORIDA MAN 'SEXUALLY ASSAULTS' STUFFED OLAF DOLL AT TARGET",
    id: 9,
  },
  {
    prompt: 'FLORIDA MAN REMOVES 9 FOOT ALLIGATOR FROM POOL',
    id: 10,
  },
  {
    prompt: 'FLORIDA MAN TRIES TO GET ALLIGATOR DRUNK, GETS BITTEN',
    id: 11,
  },
  {
    prompt: 'FLORIDA MAN HITS MECHANIC WITH GOLF CLUB FOR FIXING CAR TOO SLOW',
    id: 12,
  },
  {
    prompt:
      'FLORIDA MAN SMASHES 20 CAR WINDOWS, SAYS TRUMP OWES HIM 1 TRILLION DOLLARS',
    id: 13,
  },
  {
    prompt:
      'FLORIDA MAN BREAKS INTO HOME, COOKS BREAKFAST, TELLS OWNER TO "GO BACK TO SLEEP"',
    id: 14,
  },
  {
    prompt: 'FLORIDA MAN ARRESTED AFTER GIVING AGGRESSIVE "WET WILLY"',
    id: 15,
  },
  {
    prompt: 'FLORIDA MAN ATTACKS JOGGER WITH SWORD OVER PILE OF TRASH [VIDEO]',
    id: 16,
  },
  {
    prompt:
      'FLORIDA MAN SPRAYS NEIGHBORS WITH BUG SPRAY, HITS HIMSELF IN THE HEAD WITH NUNCHUCKS',
    id: 17,
  },
  {
    prompt:
      'FLORIDA MAN TELLS DEPUTY HE VAPES THC TO PREPARE HIMSELF FOR THE RETURN OF JESUS',
    id: 18,
  },
  {
    prompt: "FLORIDA MAN PRIES OPEN GATOR'S MOUTH TO GET HIS DOG BACK",
    id: 19,
  },
  {
    prompt: 'FLORIDA MAN BREAKS INTO HOME, BLAMES HORSE',
    id: 20,
  },
  {
    prompt:
      'FLORIDA MAN STRIPS NAKED, MASTURBATES IN FRONT OF SECURITY GUARD SHACK',
    id: 21,
  },
  {
    prompt: 'FLORIDA MAN WEARING NOTHING BUT BRA AND HAT BURGLARIZES CARS',
    id: 22,
  },
  {
    prompt: 'FLORIDA MAN CARJACKER ARRESTED BECAUSE HE CANT DRIVE STICK',
    id: 23,
  },
  {
    prompt: "FLORIDA MAN MASTURBATES OUTSIDE OF WALMART, GRABS DEPUTY'S BUTT",
    id: 24,
  },
  {
    prompt: "FLORIDA MAN CUTS OFF PENIS OF WIFE'S LOVER WITH SCISSORS",
    id: 25,
  },
  {
    prompt: '75-YEAR OLD FLORIDA MAN FIGHTS ALLIGATOR, SAVES DOG',
    id: 26,
  },
  {
    prompt:
      'FLORIDA MAN MAKES THREATS WITH SWORD AFTER GAME CONSOLE LOSES POWER',
    id: 27,
  },
  {
    prompt:
      'FLORIDA MAN TRIES TO STEAL 26 CARS FROM JAIL PARKING JUST AFTER BEING RELEASED',
    id: 28,
  },
  {
    prompt: 'DRUNKEN FLORIDA MAN BREAKS BACK JUMPING CANAL IN NISSAN VERSA',
    id: 29,
  },
  {
    prompt:
      'DRUNKEN FLORIDA MAN THREATENS TO STAB COWORKERS, STRIPS NAKED, PASSES OUT',
    id: 30,
  },
  {
    prompt: 'FLORIDA MAN THROWS FECES AT JUDGE DURING TRIAL, GETS ACQUITTED',
    id: 31,
  },
  {
    prompt:
      'NAKED FLORIDA MAN MASTURBATES IN FRONT OF HIS MOTEL WINDOW WHILE WATCHING PEOPLE WALK BY',
    id: 32,
  },
  {
    prompt: 'FLORIDA MAN DRESSED AS SPIDER-MAN SPOTTED POWER WASHING ROOF',
    id: 33,
  },
  {
    prompt:
      'FLORIDA MAN EATS CHICKEN WINGS, REFUSES TO PAY FOR THEM, PULLS OUT HIS PENIS',
    id: 34,
  },
  {
    prompt: 'FLORIDA MAN STEALS 75 POOL FLOATS SO HE CAN HAVE SEX WITH THEM',
    id: 35,
  },
  {
    prompt:
      'FLORIDA MAN ASKS COP TO HELP HIM START SCOOTER HE WAS TRYING TO STEAL',
    id: 36,
  },
  {
    prompt:
      'FLORIDA MAN THREATENS MAN WITH AX, STEALS AND CRASHES CAR, FOUND NAKED HIDING IN CHICKEN COOP',
    id: 37,
  },
  {
    prompt:
      "NAKED FLORIDA MAN DANCES AT MCDONALD'S, TRIES TO HAVE SEX WITH RAILING",
    id: 38,
  },
  {
    prompt: "FLORIDA MAN WITH COCAINE ON HIS NOSE TELLS COPS IT'S NOT HIS",
    id: 39,
  },
  {
    prompt:
      'FLORIDA MAN GOES TO RESTAURANT, STANDS ON CHAIRS, FLIPS OFF CUSTOMERS, TELLS COPS TO "GO TO DUNKIN DONUTS"',
    id: 40,
  },
  {
    prompt: 'FLORIDA MAN ARRESTED FOR ASSAULT WITH KETCHUP',
    id: 41,
  },
  {
    prompt:
      'FLORIDA MAN TRIES TO BREAK INTO ATM WITH BLOWTORCH, WELDS IT SHUT INSTEAD',
    id: 42,
  },
  {
    prompt:
      'FLORIDA MAN POURS SALT ON FLOOR OF WALMART TO GET RID OF "EVIL SPIRITS" AROUND HIM',
    id: 43,
  },
  {
    prompt:
      "FLORIDA MAN BREAKS INTO WOMAN'S HOME, WEARS HER CLOTHES, ASKS HER FOR A DRINK",
    id: 44,
  },
  {
    prompt: 'FLORIDA MAN TELLS COP HIS NAME IS "BEN DOVER"',
    id: 45,
  },
  {
    prompt: 'FLORIDA MAN ATTACKS MOM WITH CORN ON THE COB',
    id: 46,
  },
  {
    prompt: 'FLORIDA MAN ATTACKED BY PYTHON HIDING IN TOILET',
    id: 47,
  },
  {
    prompt:
      "FLORIDA MAN TELLS COPS HE'LL BEHEAD THEM, EAT THEIR EYES & TONGUES",
    id: 48,
  },
  {
    prompt: 'FLORIDA MAN HAS CONVERSATION WITH ATM BEFORE CHARGING DEPUTY',
    id: 49,
  },
  {
    prompt:
      'SHIRTLESS FLORIDA MAN STEALS FHP CRUISER, TAKES OFF DOWN HIGHWAY AT 150MPH',
    id: 50,
  },
  {
    prompt:
      'FLORIDA MAN EXPOSES GENITALS TO WOMEN WHILE RIDING WALMART SCOOTER',
    id: 51,
  },
  {
    prompt: 'FLORIDA MAN ON THE RUN FOUND HIDING INSIDE DISHWASHER',
    id: 52,
  },
  {
    prompt: 'FLORIDA MAN SLAPS FLORIDA WOMAN WITH CHEESEBURGER',
    id: 53,
  },
  {
    prompt: 'SHIRTLESS FLORIDA MAN FIGHTS TREE',
    id: 54,
  },
  {
    prompt:
      'FLORIDA MAN PLAYS BASKETBALL NAKED AT PUBLIC PARK, SAYS IT WILL ENHANCE HIS SKILL LEVEL',
    id: 55,
  },
  {
    prompt:
      'FLORIDA MAN IMPERSONATES FBI AGENT, HARASSES HOMEOWNER, LEAVES LIVE CATFISHES ON DRIVEWAY, FLEES ON BICYCLE',
    id: 56,
  },
  {
    prompt:
      "FLORIDA MAN DRIVES CADILLAC FROM SUNROOF DOWN HIGHWAY, SAYS HE'D RATHER GO TO JAIL THAN BACK TO HIS WIFE",
    id: 57,
  },
  {
    prompt:
      'NAKED FLORIDA MAN PLEASURES HIMSELF IN FRONT OF HORRIFIED ONLOOKERS',
    id: 58,
  },
  {
    prompt:
      'FLORIDA MAN ARRESTED AFTER REFUSING TO REMOVE "I EAT ASS" STICKER FROM TRUCK',
    id: 59,
  },
  {
    prompt: 'FLORIDA WOMAN PULLS ALLIGATOR OUT OF PANTS DURING TRAFFIC STOP',
    id: 60,
  },
  {
    prompt:
      'FLORIDA MAN WITH BAC OVER THREE TIMES LEGAL LIMIT CRASHES LAWNMOWER INTO COP CAR',
    id: 61,
  },
  {
    prompt:
      'NAKED FLORIDA MAN ARRESTED FOR "ACTIVELY TUGGING" GENITALS WHILE WALKING AROUND NEIGHBORHOOD',
    id: 62,
  },
  {
    prompt:
      'WIG-WEARING FLORIDA MAN ARRESTED AMONG 100 OTHERS IN EPIC DRUG BUST',
    id: 63,
  },
  {
    prompt:
      'FLORIDA MAN MASTURBATES ON BEACH BECAUSE THERE WERE "WOMEN IN THONGS"',
    id: 64,
  },
  {
    prompt:
      'SPEEDO-WEARING FLORIDA MAN FLAGS DOWN DEPUTIES TO SHOW OFF HIS POT PLANT',
    id: 65,
  },
  {
    prompt: 'FLORIDA MAN WEARING BONNET & FLOWER DRESS STEALS BABY FORMULA',
    id: 66,
  },
  {
    prompt: 'FLORIDA MAN RESISTS ARREST BY SINGING KARAOKE',
    id: 67,
  },
  {
    prompt:
      'FLORIDA MAN SAYS HE\'LL "SHOOT ALL THE EMPLOYEES" AT PET STORE OVER SICK PUPPIES',
    id: 68,
  },
  {
    prompt: "DRUNKEN FLORIDA MAN TELLS COPS HE'S JASON BOURNE",
    id: 69,
  },
  {
    prompt:
      'FLORIDA MAN BREAKS INTO OFFICE, PUTS SIGN IN WINDOW: "SECRETARY WANTED, $17/HOUR"',
    id: 70,
  },
  {
    prompt: 'FLORIDA MAN THINKS HIS SHOPPING CART IS A STREET LEGAL CAR',
    id: 71,
  },
  {
    prompt:
      'FLORIDA MAN THREATENS TO KILL LANDSCAPER AFTER LEAVING GRASS CLIPPINGS ON HIS LAWN',
    id: 72,
  },
  {
    prompt:
      'FLORIDA MAN ON METH ATTACKS MATTRESS, WAS LOOKING FOR MAN "HIDING INSIDE"',
    id: 73,
  },
  {
    prompt: 'FLORIDA MAN SAYS HE\'S "TOO FAT" FOR DUI TEST',
    id: 74,
  },
  {
    prompt: 'FLORIDA MAN STABS NEPHEW BECAUSE HE TOOK TOO LONG IN THE BATHROOM',
    id: 75,
  },
  {
    prompt: 'FLORIDA MAN PRETENDING TO BE COP PULLS OVER ACTUAL COP',
    id: 76,
  },
  {
    prompt: 'FLORIDA MAN GETS BEAT UP BY THE EASTER BUNNY',
    id: 77,
  },
  {
    prompt: "FLORIDA MAN'S HOMEMADE BOMB GOES FLYING INTO NEIGHBOR'S BACKYARD",
    id: 78,
  },
  {
    prompt:
      'FLORIDA MAN ADVERTISES WEAPONS CLASS BY PULLING PANTS DOWN & EXPOSING HIMSELF TO TRAFFIC',
    id: 79,
  },
  {
    prompt: 'FLORIDA MAN HIDES DRUGS IN HIS BUTT CRACK',
    id: 80,
  },
  {
    prompt:
      'FLORIDA MAN WALKS OUT OF STORE WITH 12 BOXES OF GOLF BALLS IN HIS PANTS',
    id: 81,
  },
  {
    prompt: '80 YEAR OLD FLORIDA MAN FIGHTS ALLIGATOR',
    id: 82,
  },
  {
    prompt: 'NAKED FLORIDA MAN BREAKS INTO CONCESSION STAND TO STEAL HOTDOGS',
    id: 83,
  },
  {
    prompt:
      'FLORIDA MAN BURGLAR CLOBBERED BY 65-YEAR OLD FLORIDA WOMAN WITH BASEBALL BAT',
    id: 84,
  },
  {
    prompt: 'MACHETE-WIELDING FLORIDA MAN BLOCKS TRAFFIC, HITS CAR',
    id: 85,
  },
  {
    prompt: 'FLORIDA MAN SHOOTS WOMAN WITH WATER GUN FILLED WITH HIS OWN URINE',
    id: 86,
  },
  {
    prompt: 'FLORIDA MAN EXPOSES GENITALS IN TRAFFIC',
    id: 87,
  },
  {
    prompt: "FLORIDA MAN STRIPS NAKED, POOPS IN FAMILY'S YARD",
    id: 88,
  },
  {
    prompt: 'FLORIDA MAN ON MOTORCYCLE TAUNTS DEPUTIES, THEN CRASHES INTO TREE',
    id: 89,
  },
  {
    prompt:
      'FLORIDA MAN MAYOR SMOKES CRACK, EATS METH, PRACTICES MEDICINE WITHOUT LICENSE, FIRES ON SWAT TEAM',
    id: 90,
  },
  {
    prompt: 'FLORIDA MAN SHOWS UP TO HOSPITAL NAKED, SAYS HE\'S "READY TO GO"',
    id: 91,
  },
  {
    prompt:
      'FLORIDA MAN DRIVING AROUND WITH PANTS DOWN SAYS HE WAS JUST WORKING OUT',
    id: 92,
  },
  {
    prompt:
      'FLORIDA MAN THREATENS TO DESTROY EVERYONE WITH HIS ARMY OF TURTLES',
    id: 93,
  },
  {
    prompt:
      'FLORIDA MAN STEALS CAR BACK FROM TOWING COMPANY, SMASHES THROUGH GATE',
    id: 94,
  },
  {
    prompt: 'FLORIDA MAN BACK IN JAIL FOR MURDER MINUTES AFTER BEING RELEASED',
    id: 95,
  },
  {
    prompt: 'FLORIDA MAN ATTACKS PARENTS OVER PORK CHOP',
    id: 96,
  },
  {
    prompt:
      'FLORIDA MAN BREAKS INTO VILLAGE HALL, CAUSES $500,000 IN DAMAGES, SMEARS BLOOD ON AMERICAN FLAG',
    id: 97,
  },
  {
    prompt:
      'FLORIDA MAN STEALS FROM KMART DAYS AFTER BUYING $8 MILLION PRIVATE ISLAND',
    id: 98,
  },
  {
    prompt:
      'DRUNK, SHIRTLESS FLORIDA MAN SHOVELS SPAGHETTI INTO HIS MOUTH AT OLIVE GARDEN',
    id: 99,
  },
  {
    prompt: 'FLORIDA MAN PRETENDING TO BE COP FOR YOUTUBE VIEWS GETS ARRESTED',
    id: 100,
  },
  {
    prompt:
      'FAMILY COMES HOME TO FIND DRUNKEN FLORIDA MAN SLEEPING ON PORCH WITH LOADED SHOTGUN',
    id: 101,
  },
  {
    prompt: 'FLORIDA MAN FIRES GUN INSIDE HOME, SHATTERS TOILET',
    id: 102,
  },
  {
    prompt:
      'FLORIDA MAN BONDS OUT OF JAIL, THEN BURGLARIZES CARS IN JAIL PARKING LOT',
    id: 103,
  },
  {
    prompt: '7 TIMES FLORIDA MAN CHANNELED HIS INNER COMIC BOOK HERO',
    id: 104,
  },
  {
    prompt:
      "THONG-WEARING FLORIDA MAN FOUND IN MAN'S BACKYARD BUILDING A SHED AND THROWING CHAIRS",
    id: 105,
  },
  {
    prompt:
      'FLORIDA MAN ATTACKS WITH RAZOR BLADE, MACHETE IN ARGUMENT OVER SQUEEGEE',
    id: 106,
  },
  {
    prompt:
      'DRUNKEN FLORIDA MAN DRIVES AROUND ON GOLF CART, 5 BOTTLES OF FIREBALL FOUND INSIDE',
    id: 107,
  },
  {
    prompt: 'FLORIDA MAN STABS MAN IN ARGUMENT OVER DONUTS',
    id: 108,
  },
  {
    prompt: 'FLORIDA MAN STEALS NEARLY 6K WORTH OF SUNGLASSES',
    id: 109,
  },
  {
    prompt: "FACE-EATING FLORIDA MAN CLAIMS HE WAS 'HALF-MAN, HALF-DOG'",
    id: 110,
  },
  {
    prompt:
      'FLORIDA MAN APPLIES FOR JOB, GETS ARRESTED FOR ATTEMPTED MURDER 20 YEARS AGO',
    id: 111,
  },
  {
    prompt:
      "FLORIDA MAN SAYS HE'S 'ARCHANGEL MICHAEL', TRIES TO BLOW UP 16 GOVERNMENT VEHICLES",
    id: 112,
  },
  {
    prompt: 'FLORIDA MAN FAKES ROBBERY TO GET OUT OF WORK',
    id: 113,
  },
  {
    prompt:
      'FLORIDA MAN ATTACKS HIS MOM BECAUSE SHE REFUSED TO DRESS HIS MANNEQUIN',
    id: 114,
  },
  {
    prompt: 'DRUNKEN FLORIDA MAN GOES TO JAIL BECAUSE HE WANTED EGG ROLLS',
    id: 115,
  },
  {
    prompt:
      'FLORIDA MAN CALLS 911, SAYS HE PAID FOR SEX BUT GOT SCAMMED OUT OF $500',
    id: 116,
  },
  {
    prompt: 'FLORIDA MAN SHOOTS HIS COUSIN OVER SUNGLASSES',
    id: 117,
  },
  {
    prompt: 'FLORIDA MAN ATTACKED BY FLORIDA SQUIRREL',
    id: 118,
  },
  {
    prompt: 'FLORIDA MAN MASTURBATES WHILE WAITING AT SOCIAL SECURITY OFFICE',
    id: 119,
  },
  {
    prompt: 'FLORIDA MAN THROWS PANCAKE BATTER ON WOMAN',
    id: 120,
  },
  {
    prompt:
      "FLORIDA MAN FOUND PASSED OUT DRUNK BEHIND THE WHEEL IN A WENDY'S DRIVE-THRU LINE",
    id: 121,
  },
  {
    prompt:
      'FLORIDA MAN WEARING SPIDER MAN MASK ROBS STORE FOR BOOZE, CIGARETTES',
    id: 122,
  },
  {
    prompt: 'FLORIDA MAN CALLS 911 AFTER FINDING IGUANA SWIMMING IN TOILET',
    id: 123,
  },
  {
    prompt:
      'FLORIDA MAN STUFFS A POUND OF MARIJUANA IN HIS PANTS DURING TRAFFIC STOP',
    id: 124,
  },
  {
    prompt: 'FLORIDA MAN PRESSURE WASHES HIS NEIGHBOR',
    id: 125,
  },
  {
    prompt:
      'FLORIDA MAN STEALS $33,000 OF RARE COINS, REDEEMS AT COINSTAR FOR 30 DOLLARS',
    id: 126,
  },
  {
    prompt:
      "FLORIDA MAN GOES TO SHERIFF'S OFFICE, STEALS FLAG, EXPOSES HIMSELF",
    id: 127,
  },
  {
    prompt: 'CROSS DRESSING FLORIDA MAN SENTENCED TO 6 YEARS FOR BURGLARIZING',
    id: 128,
  },
  {
    prompt: 'FLORIDA MAN STEALS TOILET, OTHER ITEMS FROM HOME DEPOT',
    id: 129,
  },
  {
    prompt: 'FLORIDA MAN ATTACKS WOMAN WITH BAG OF TORTILLA CHIPS',
    id: 130,
  },
  {
    prompt: 'FLORIDA MAN TAKES GRENADE LAUNCHER TO AIRPORT',
    id: 131,
  },
  {
    prompt: 'NAKED FLORIDA MAN RIDES BICYCLE BACKWARDS ON HIGHWAY',
    id: 132,
  },
  {
    prompt: 'FLORIDA MAN ATTACKS COWORKER WITH MACHETE',
    id: 133,
  },
  {
    prompt: 'FLORIDA MAN CAUGHT ON CAMERA LICKING DOORBELLS',
    id: 134,
  },
  {
    prompt:
      'FLORIDA MAN THREATENS TO CUT OFF BUTTOCKS WITH MACHETE OVER POTATO CHIPS',
    id: 135,
  },
  {
    prompt: "FLORIDA MAN SAYS MULTIPLE SYRINGES FOUND IN RECTUM AREN'T HIS",
    id: 136,
  },
  {
    prompt:
      'FLORIDA MAN SAYS ALIENS HAVE LANDED, BURNS DOWN HOUSE STOCKED WITH FLAMETHROWERS AND AMMO',
    id: 137,
  },
  {
    prompt: 'FLORIDA MAN SHOVES FOOTLONG SANDWICH DOWN HIS PANTS',
    id: 138,
  },
  {
    prompt:
      'FLORIDA MAN GOES TO JOB INTERVIEW, THEN STEALS SHOES TO GIVE TO HIS MOM',
    id: 139,
  },
  {
    prompt:
      'FLORIDA MAN CALLS 911, TELLS COPS: "TAKE ME TO JAIL, MOTHERF*CKER!"',
    id: 140,
  },
  {
    prompt: 'WIDE NECKED FLORIDA MAN ENTERS MUGSHOT HALL OF FAME',
    id: 141,
  },
  {
    prompt:
      'NAKED FLORIDA MAN BREAKS INTO RESTAURANT TO EAT RAMEN NOODLES, PLAY BONGOS',
    id: 142,
  },
  {
    prompt:
      'FLORIDA MAN DRIVING CAR FULL OF STOLEN MAIL CRASHES INTO TRAILER FULL OF ALPACAS',
    id: 143,
  },
  {
    prompt:
      'NAKED FLORIDA MAN DRINKS 2 LITERS OF VODKA, BURNS DOWN HOUSE BAKING COOKIES ON GEORGE FOREMAN GRILL',
    id: 144,
  },
  {
    prompt: 'FLORIDA MAN SHOVES $100 OF ICED COFFEE IN HIS PANTS',
    id: 145,
  },
  {
    prompt:
      'FLORIDA MAN GOES TO JAPANESE STEAKHOUSE, STARTS STRIPPING IN FRONT OF CUSTOMERS',
    id: 146,
  },
  {
    prompt:
      "FLORIDA MAN THREATENS TO BLOW UP LESBIAN WOMAN'S HOME AFTER DENYING HIS SEXUAL ADVANCES",
    id: 147,
  },
  {
    prompt: 'FLORIDA MAN STRIPS NAKED AT MALL, MAKES WHOOPING SOUNDS AT POLICE',
    id: 148,
  },
  {
    prompt:
      'FLORIDA MAN BRINGS LIVE GATOR INTO CONVENIENCE STORE, CHASES CUSTOMERS',
    id: 149,
  },
  {
    prompt:
      'FLORIDA MAN SWINGS ANCHOR AT BEACHGOERS BECAUSE THEY RUINED HIS CHICKEN',
    id: 150,
  },
  {
    prompt: 'ARMLESS FLORIDA MAN STABS TOURIST WITH SCISSORS HELD IN HIS FEET',
    id: 151,
  },
  {
    prompt: 'FLORIDA MAN BREAKS INTO HOME, GETS NAKED, COOKS SPAGHETTI',
    id: 152,
  },
  {
    prompt:
      'FLORIDA MAN PULLED OVER DURING TRAFFIC STOP CLAIMS DOG WAS DRIVING',
    id: 153,
  },
  {
    prompt:
      'FLORIDA MAN DRIVES STOLEN CAR INTO DITCH, HAS DIAPER-WEARING MONKEY ATTACHED TO HIM',
    id: 154,
  },
  {
    prompt:
      'FLORIDA MAN UPSET OVER LOW QUALITY METH CALLS COPS TO HAVE THEM TEST IT',
    id: 155,
  },
  {
    prompt:
      'FLORIDA MAN BREAKS INTO HOME, STEALS ALCOHOL, POOPS ON FLOOR, FALLS ASLEEP ON COUCH',
    id: 156,
  },
  {
    prompt: 'THIEVING FLORIDA MAN GETS ARM STUCK IN CHURCH DONATION BOX',
    id: 157,
  },
  {
    prompt: 'FLORIDA MAN ROBS 7 ELEVEN BY POINTING FINGER LIKE A GUN AT CLERK',
    id: 158,
  },
  {
    prompt: 'FLORIDA MAN PUNCHES MAILBOXES, GETS TASED 4 TIMES BY COPS',
    id: 159,
  },
  {
    prompt:
      'FLORIDA MAN SAYS SCOOTER HE PURCHASED CAME WITH METH & OTHER DRUGS INSIDE',
    id: 160,
  },
  {
    prompt: 'FLORIDA MAN OFFERS $10,000 FOR SAFE RETURN OF HIS STOLEN MONKEY',
    id: 161,
  },
  {
    prompt: 'FLORIDA MAN STEALS SWAN BOAT, GETS STRANDED ON LAKE EOLA FOUNTAIN',
    id: 162,
  },
  {
    prompt:
      'FLORIDA MAN GOES TO STEAK N SHAKE, URINATES ON FLOOR, GOES TO SLEEP',
    id: 163,
  },
  {
    prompt:
      'FLORIDA MAN CAUGHT STEALING BEER SAYS HE WAS JUST EXCHANGING FOR COLD ONES',
    id: 164,
  },
  {
    prompt: 'FLORIDA MAN SWINGS DILDO AT COPS',
    id: 165,
  },
  {
    prompt: 'FLORIDA MAN TRIES TO BREAK INTO VEHICLE FULL OF COPS',
    id: 166,
  },
  {
    prompt: 'FLORIDA MAN STEALS ATM FROM STRIP CLUB',
    id: 167,
  },
  {
    prompt:
      "FLORIDA MAN SHOOTS UP METH, HOWLS AND STOMPS ON ROOFS, TELLS COPS HE'S WAITING FOR DEA",
    id: 168,
  },
  {
    prompt: 'FLORIDA MAN DOES DONUTS ON SCOOTER, CHASES WOMAN',
    id: 169,
  },
  {
    prompt:
      'FLORIDA MAN GETS IN 8 HOUR STANDOFF WITH POLICE, SAYS HE WAS JUST SHOOTING RATS IN HIS BACKYARD THE WHOLE TIME',
    id: 170,
  },
  {
    prompt: "NAKED FLORIDA MAN RUNS INTO WOMAN'S HOME, TRIES ON HER CLOTHES",
    id: 171,
  },
  {
    prompt: 'FLORIDA MAN HIDES $1,000 IN RECTUM',
    id: 172,
  },
  {
    prompt:
      'FLORIDA MAN PULLS OUT FAKE AR-15 IN MCDONALDS AFTER BEING DENIED ICE CREAM',
    id: 173,
  },
  {
    prompt:
      'FLORIDA MAN SAYS HOOKAH SMOKING CATERPILLAR TOLD HIM TO CAUSE 100K IN DAMAGES TO LIQUOR STORE',
    id: 174,
  },
  {
    prompt: 'FLORIDA MAN ARRESTED AFTER COCAINE-FUELED 100MPH CHASE',
    id: 175,
  },
  {
    prompt:
      'FLORIDA MAN CLAIMING TO HAVE AIDS BRANDISHES NEEDLE: "I WILL STICK YOU"',
    id: 176,
  },
  {
    prompt: 'FLORIDA MAN TRIES TO ROB FORMER WWE WRESTLER, FAILS MISERABLY',
    id: 177,
  },
  {
    prompt: 'FLORIDA MAN STEALS FORKLIFT BECAUSE HE WAS TIRED OF WALKING',
    id: 178,
  },
  {
    prompt: 'FLORIDA MAN UNPLUGS BOUNCE HOUSE WITH KIDS INSIDE',
    id: 179,
  },
  {
    prompt: 'FLORIDA MAN TRIES TO HIDE NEARLY 100 HEROIN PILLS UP HIS BUTT',
    id: 180,
  },
  {
    prompt:
      'FLORIDA MAN WEARING BUCKET ON HEAD BREAKS INTO PET SHOP, STEALS PIGEONS',
    id: 181,
  },
  {
    prompt: "FLORIDA MAN CALLS 911 BECAUSE HIS MOM WON'T PAY FOR IHOP",
    id: 182,
  },
  {
    prompt: 'FLORIDA MAN TRIES TO STEAL BEER, BITES EMPLOYEE',
    id: 183,
  },
  {
    prompt:
      'FLORIDA MAN LEAVING STRIP CLUB RUNS HIMSELF OVER WITH HIS OWN TRUCK',
    id: 184,
  },
  {
    prompt: 'NAKED FLORIDA MAN ARRESTED NEAR SCHOOL BUS STOP',
    id: 185,
  },
  {
    prompt:
      "FLORIDA MAN NAMED 'SHAQUILLE O'NEAL' STEALS VETERAN'S WHEELCHAIR, CRASHES CAR",
    id: 186,
  },
  {
    prompt: 'FLORIDA MAN INSTALLS GIANT PENIS MAILBOX',
    id: 187,
  },
  {
    prompt: 'FLORIDA MAN BREAKS INTO HOME, COOKS AND EATS PIZZA WHILE INSIDE',
    id: 188,
  },
  {
    prompt: "FLORIDA MAN BREAKS INTO WOMAN'S HOME TO PET FAMILY CAT",
    id: 189,
  },
  {
    prompt:
      'NAKED FLORIDA MAN DRIVES AROUND WITH ELECTRICAL WIRES WRAPPED AROUND PENIS',
    id: 190,
  },
  {
    prompt:
      'FLORIDA MAN CALLS HIMSELF SATAN, THREATENS TO KILL IF NOT GIVEN A CAR',
    id: 191,
  },
  {
    prompt: 'FLORIDA MAN ATTACKS MAN WITH PICKAXE IN METH-FUELED RAGE',
    id: 192,
  },
  {
    prompt: 'FLORIDA MAN HOLDING SIX-PACK OF BEER SHOOTS RIFLE AT PASSING CARS',
    id: 193,
  },
  {
    prompt:
      'FLORIDA MAN ORDERS PIZZA, STUFFS IT INTO HIS MOUTH INSTEAD OF PAYING',
    id: 194,
  },
  {
    prompt: "FLORIDA MAN TAKES A LEAK IN SHERIFF'S BACKYARD",
    id: 195,
  },
  {
    prompt: 'FLORIDA MAN JACKS OFF IN PICKUP TRUCK OUTSIDE WALGREENS',
    id: 196,
  },
  {
    prompt: 'FLORIDA MAN STABS FATHER FOR TRYING TO CIRCUMCISE HIM',
    id: 197,
  },
  {
    prompt: 'TUTU WEARING FLORIDA MAN BREAKS INTO FARMERS MARKET',
    id: 198,
  },
  {
    prompt:
      "350-POUND FLORIDA MAN ATTEMPTS TO STEAL 2 TV'S FROM WALMART, TRIPS AFTER PANTS FALL DOWN",
    id: 199,
  },
  {
    prompt:
      "FLORIDA MAN'S ATTEMPTED CARJACKING THWARTED BY INABILITY TO DRIVE A MANUAL TRANSMISSION",
    id: 200,
  },
  {
    prompt:
      'INFAMOUS FLORIDA MAN WITH HALF A HEAD ARRESTED FOR ATTEMPTED MURDER',
    id: 201,
  },
  {
    prompt: 'FLORIDA MAN STUFFS STEAK AND LOBSTER IN HIS PANTS',
    id: 202,
  },
  {
    prompt: 'FLORIDA MAN BREAKS INTO HOME, EATS BOLOGNA AND TAKES A NAP',
    id: 203,
  },
  {
    prompt: 'FLORIDA MAN WITH SHOTGUN DEMANDS STORE FIX HIS PHONE',
    id: 204,
  },
  {
    prompt: 'FLORIDA MAN EXPOSES HIMSELF TO WOMAN AT WAL-MART',
    id: 205,
  },
  {
    prompt: 'FLORIDA MAN WEED WHACKS HIS NEIGHBOR',
    id: 206,
  },
  {
    prompt: 'FLORIDA MAN ARRESTED FOR ATTACKING GIRLFRIEND WITH DILDO',
    id: 207,
  },
  {
    prompt: 'FLORIDA MAN TRIES TO STEAL YACHT, PARTIALLY SINKS IT INSTEAD',
    id: 208,
  },
  {
    prompt: 'FLORIDA MAN BECOMES CATEGORY ON JEOPARDY',
    id: 209,
  },
  {
    prompt: 'FLORIDA MAN TRIES TO SHOOT PUPPY, PUPPY SHOOTS HIM INSTEAD',
    id: 210,
  },
  {
    prompt:
      'FLORIDA WOMAN WHO STOLE FROM WALMART PLANS TO APPLY FOR JOB - AT WALMART',
    id: 211,
  },
  {
    prompt:
      'FLORIDA MAN ON THE RUN DARES COPS TO CATCH HIM ON FACEBOOK, GETS ARRESTED',
    id: 212,
  },
  {
    prompt: "FLORIDA WOMAN ROBS ARBY'S, CALLS A CAB TO MAKE GETAWAY",
    id: 213,
  },
  {
    prompt: 'FLORIDA MAN ROBS SUBWAY WHILE ON CELL PHONE',
    id: 214,
  },
  {
    prompt: 'FLORIDA MAN RIDES MANATEE, TALKS SMACK TO COPS',
    id: 215,
  },
  {
    prompt: 'FLORIDA MAN STEALS MORE THAN $45000 WORTH OF SOCKS',
    id: 216,
  },
  {
    prompt: 'FLORIDA MAN ROBS CONVENIENCE STORE WHILE WEARING LUCHADOR MASK',
    id: 217,
  },
  {
    prompt: 'FLORIDA WOMAN COOKS METH IN LAUNDRY SHED',
    id: 218,
  },
  {
    prompt: 'FLORIDA MAN PAYS FOR ORDER AT TACO BELL, THEN ROBS IT',
    id: 219,
  },
  {
    prompt:
      'FLORIDA MAN SAYS SLURRED SPEECH IS BECAUSE OF WISDOM TEETH, NOT BOOZE',
    id: 220,
  },
  {
    prompt: "FLORIDA WOMAN MAKES BOMB THREAT TO HALT BOYFRIEND'S URINE SAMPLE",
    id: 221,
  },
  {
    prompt: 'FLORIDA MAN BEACHES YACHT AFTER TOO MANY LONG ISLAND ICED TEAS',
    id: 222,
  },
  {
    prompt: 'SHIRTLESS FLORIDA MAN PUNCHES AT CARS AFTER DISRUPTING BAR SHOW',
    id: 223,
  },
  {
    prompt: "FLORIDA MAN STEALS PATROL CAR, ASKS 'THIS IS A FELONY?'",
    id: 224,
  },
  {
    prompt:
      "FLORIDA MAN GETS JAIL FOR SECOND DRUNKEN RAMPAGE IN GOLF CART AT PARENTS' RETIREMENT COMMUNITY",
    id: 225,
  },
  {
    prompt:
      'FLORIDA MAN USES HIS OWN WANTED POSTER AS FACEBOOK PROFILE PICTURE',
    id: 226,
  },
  {
    prompt: 'FLORIDA MAN IN DINOSAUR COSTUME HOLDING AIR RIFLE ARRESTED',
    id: 227,
  },
  {
    prompt: 'FLORIDA MAN USES MOUNTAIN DEW AS FAKE URINE FOR DRUG TEST',
    id: 228,
  },
  {
    prompt: '27TH ARREST FOR BIKINI-CLAD FLORIDA MAN',
    id: 229,
  },
  {
    prompt:
      'FLORIDA MAN VIDEOTAPED CATCHING GATOR WITH BARE HANDS FACES FELONY CHARGES',
    id: 230,
  },
  {
    prompt: 'FLORIDA WOMAN RECORDS CLOSE BEAR ENCOUNTER',
    id: 231,
  },
  {
    prompt: "100 CHICKENS FOUND LIVING IN FLORIDA WOMAN'S HOUSE",
    id: 232,
  },
  {
    prompt: 'FLORIDA MAN NAMED VLADIMIR PUTIN ARRESTED FOR SCREAMING IN PUBLIX',
    id: 233,
  },
  {
    prompt: 'FLORIDA MAN STEALS $10K IN LOTTO TICKETS, PICTURE LEADS TO ARREST',
    id: 234,
  },
  {
    prompt: "FLORIDA MAN FOUND HAVING SEX, SAID 'IT WAS HIS DUTY'",
    id: 235,
  },
  {
    prompt: 'FLORIDA MAN CAUGHT EATING METH SOAKED DRAWINGS SMUGGLED IN JAIL',
    id: 236,
  },
  {
    prompt:
      'POLICE: FLORIDA MAN LINES GARAGE WITH MORE THAN $100K IN STOLEN AMAZON ORDERS',
    id: 237,
  },
  {
    prompt: 'FLORIDA MAN FAKED BEING A COP TO AVOID PAYING $11',
    id: 238,
  },
  {
    prompt:
      'FLORIDA MAN THREATENED HIS BROTHER WITH A KNIFE BECAUSE HE CALLED HIM FAT',
    id: 239,
  },
  {
    prompt: 'FLORIDA MAN THREATENS TO FEED CHILDREN TO ALLIGATORS',
    id: 240,
  },
  {
    prompt: 'DRUNKEN FLORIDA MAN FIRES GUN IN AIR WHILE DRIVING',
    id: 241,
  },
  {
    prompt: 'FLORIDA MAN BREAKS INTO HOME, STEALS SAUSAGES',
    id: 242,
  },
  {
    prompt: "FLORIDA MAN KILLS COUPLE, TRIES TO BITE MAN'S FACE OFF",
    id: 243,
  },
  {
    prompt:
      'FLORIDA MAN MASTURBATES IN PARK BATHROOM, PAYS CHILDREN NOT TO TELL',
    id: 244,
  },
  {
    prompt: 'FLORIDA MAN CLAIMING TO BE PASTOR CHARGED WITH FRAUD',
    id: 245,
  },
  {
    prompt:
      "FLORIDA MAN AND GIRLFRIEND ATTACK GRANDMOTHER WHO WOULDN'T DRIVE THEM SOMEWHERE TO HAVE SEX",
    id: 246,
  },
  {
    prompt: 'FLORIDA MAN TORCHES CHURCH TO GET AT "DEVIL WORSHIPPERS"',
    id: 247,
  },
  {
    prompt: "JUDGE UNAMUSED AT FLORIDA MAN'S TWERKING ABILITY",
    id: 248,
  },
  {
    prompt:
      'FLORIDA MAN BANNED FROM ORDERING PIZZA AFTER HARASSING RESTAURANTS',
    id: 249,
  },
  {
    prompt: "FLORIDA MAN'S ROBBERY FOILED BY ANGRY BIRDS BACKPACK",
    id: 250,
  },
  {
    prompt: 'FLORIDA MAN KILLS SOMEONE ON HIS WAY TO MURDER ANOTHER',
    id: 251,
  },
  {
    prompt:
      'FLORIDA WOMAN ACCUSED OF ALLOWING SONS TO SHOOT BBS AT HOMELESS MAN',
    id: 252,
  },
  {
    prompt: 'FLORIDA MAN TRIPPED ON ACID, ATTACKED COPS AT THEME PARK',
    id: 253,
  },
  {
    prompt:
      "FLORIDA MAN PUNCHED GEORGE ZIMMERMAN AFTER HE BRAGGED HE'S 'THAT GUY WHO KILLED TRAYVON MARTIN'",
    id: 254,
  },
  {
    prompt: "FLORIDA WOMAN DOESN'T PAY TABS, TAKES SWING AT OFFICER",
    id: 255,
  },
  {
    prompt: 'FLORIDA WOMAN SUES AIRLINE AFTER DROPPING LUGGAGE ON HERSELF',
    id: 256,
  },
  {
    prompt: 'FLORIDA MAN ATTACKS PERSON OVER PARKING SPACE',
    id: 257,
  },
  {
    prompt: "FLORIDA MAN PLACES BUCKET BOMB IN LANDLORD'S HOME",
    id: 258,
  },
  {
    prompt:
      'FLORIDA MAN SICK OF HIS $1000000 ISLAND, WANTS TO TRADE FOR A PORSCHE 918',
    id: 259,
  },
  {
    prompt: 'FLORIDA MAN PUNCHES ELDERLY WOMAN TRYING TO STOP ROBBERY',
    id: 260,
  },
  {
    prompt: 'FLORIDA MAN ATTACKS FLAMINGO AT BUSCH GARDENS, POLICE SAY',
    id: 261,
  },
  {
    prompt:
      "FLORIDA MAN TEARS UP YARD AFTER WOMAN POSTS BAD REVIEW OF HIS WIFE'S BUSINESS",
    id: 262,
  },
  {
    prompt: 'FLORIDA MAN STABS WIFE DURING ARGUMENT OVER PEELING MANGOES',
    id: 263,
  },
  {
    prompt: 'FLORIDA MAN JUMPS OFF BOAT, HIDES IN WATER TO EVADE AUTHORITIES',
    id: 264,
  },
  {
    prompt: 'FLORIDA WOMAN SHOOTS SELF WHILE USING SNAPCHAT, DEPUTIES SAY',
    id: 265,
  },
  {
    prompt: 'FLORIDA MAN SMACKS TOURIST WITH SHOVEL',
    id: 266,
  },
  {
    prompt:
      'FLORIDA MAN CHARGED WITH PICKING MAGIC MUSHROOMS WHILE CARRYING AN ALLIGATOR',
    id: 267,
  },
  {
    prompt: 'FLORIDA MAN SENDS TRUCK FLYING, BRINGS DOWN INTERSTATE SIGN',
    id: 268,
  },
  {
    prompt: "FLORIDA MAN'S BOAT BURNS AFTER USING THE BATHROOM",
    id: 269,
  },
  {
    prompt:
      "FLORIDA WOMAN BIT OFF BABYSITTER'S LIP DURING FIGHT OVER CRYING CHILD",
    id: 270,
  },
  {
    prompt: 'DEPUTIES: FLORIDA MAN USED DIRTY POOL TO BAPTIZE BOY',
    id: 271,
  },
  {
    prompt:
      "FLORIDA MAN ON 'MOLLY' CHASED GHOSTS WITH MACHETE, ENDANGERED KIDS",
    id: 272,
  },
  {
    prompt:
      'FLORIDA MAN SAYS COPS MISTOOK KRISPY KREME DOUGHNUT GLAZE FOR METH AND ARRESTED HIM',
    id: 273,
  },
  {
    prompt: 'FLORIDA MAN ARRESTED FOR ASSAULT, GIVES ALIAS "DICKFACE JOHNSON"',
    id: 274,
  },
  {
    prompt: 'FLORIDA MAN THROWS SALSA JAR AT CAR IN ROAD RAGE ATTACK',
    id: 275,
  },
  {
    prompt: "FLORIDA MAN BITES NEIGHBOR'S EAR OFF OVER A CIGARETTE",
    id: 276,
  },
  {
    prompt:
      'NAKED FLORIDA WOMAN THREATENED DEPUTIES WITH LIGHTER, PROPANE TANK',
    id: 277,
  },
  {
    prompt: "FLORIDA MAN SHOOTS AT 'POKEMON GO' PLAYERS OUTSIDE HOUSE",
    id: 278,
  },
  {
    prompt: 'FLORIDA MAN ROBS PIZZA DELIVERY MAN, SOILS HIMSELF',
    id: 279,
  },
  {
    prompt:
      'FLORIDA MAN ACCUSED OF THREATENING TO KILL FAMILY WITH SAMURAI SWORD, DEPUTIES SAY',
    id: 280,
  },
  {
    prompt: 'FLORIDA MAN USES ELECTRIC GUITAR IN FAILED ROBBERY',
    id: 281,
  },
  {
    prompt:
      'FLORIDA MAN ROBS BANK, COVERS HIMSELF IN FECES TO TRY TO ESCAPE CUSTODY',
    id: 282,
  },
  {
    prompt:
      "FLORIDA MAN BREAKS INTO EX'S HOME, FOUND WITH BACKPACK OF SEX TOYS",
    id: 283,
  },
  {
    prompt: "FLORIDA MAN FIGHTS TO KEEP PIZZA-LOVING PET ALLIGATOR 'GWENDOLYN'",
    id: 284,
  },
  {
    prompt: 'FLORIDA MAN TASERED AFTER THROWING FOOD AT TACO BELL EMPLOYEES',
    id: 285,
  },
  {
    prompt: "FLORIDA MAN LEAVES PACKAGE LABELED 'BOMB' AT GAS STATION",
    id: 286,
  },
  {
    prompt: 'FLORIDA MAN ARRESTED FOR STABBING ANOTHER MAN OVER $2 DEBT',
    id: 287,
  },
  {
    prompt: 'POLICE: FLORIDA MAN FORGETS TO UNTIE BOAT WHILE STEALING IT',
    id: 288,
  },
  {
    prompt:
      'FLORIDA MAN ARRESTED AFTER DRUNKEN ATTEMPT TO LEARN HOW TO USE A SHOTGUN',
    id: 289,
  },
  {
    prompt: "COPS: ERRATIC FLORIDA MAN ON 'MOLLY' CARRIES BABY NEAR BUSY ROAD",
    id: 290,
  },
  {
    prompt: 'FLORIDA MAN WITH NO PANTS IS ARRESTED AFTER A PURSUIT',
    id: 291,
  },
  {
    prompt:
      'FLORIDA WOMAN GOES TO CAR DEALERSHIP, PRETENDS TO BE MANAGER, FIRES EMPLOYEES',
    id: 292,
  },
  {
    prompt:
      'FLORIDA MAN ACCUSED OF GROPING 6 PEOPLE AT DISNEY WATER PARK, BLAMES BROKEN GLASSES',
    id: 293,
  },
  {
    prompt: 'FLORIDA MAN STEALS AMBULANCE WITH EMT INSIDE',
    id: 294,
  },
  {
    prompt:
      'FLORIDA MAN APPEARS TO HAVE SEX WITH TREE IN VIEW OF PASSING DRIVERS',
    id: 295,
  },
  {
    prompt:
      "FLORIDA MAN UNAWARE HE'S NOT ALLOWED TO SHOOT AT STRIP CLUB FROM HIS VEHICLE",
    id: 296,
  },
  {
    prompt: 'FLORIDA MAN BLOWS HIS HAND OFF WITH FIREWORK',
    id: 297,
  },
  {
    prompt:
      'FLORIDA MAN ACCUSED OF USING MAKESHIFT FLAMETHROWER TO THREATEN WOMAN',
    id: 298,
  },
  {
    prompt:
      'FLORIDA MAN DECAPITATES 875-YEAR-OLD STATUE, THREATENS TO SHOOT UP CHURCH',
    id: 299,
  },
  {
    prompt: 'FLORIDA MAN PULLS AK-47 DURING FAMILY DISPUTE AT GROCERY STORE',
    id: 300,
  },
  {
    prompt:
      'FLORIDA MAN CLAIMS HE INVENTED IPHONE IN 1992, SUES APPLE FOR $10 BILLION',
    id: 301,
  },
  {
    prompt: 'FLORIDA MAN EVICTED FROM TRAILER PARK; POURS POOP IN POOL',
    id: 302,
  },
  {
    prompt: 'FLORIDA MAN STEALS VAN SO HE CAN DRIVE TO WAFFLE HOUSE',
    id: 303,
  },
  {
    prompt: "FLORIDA MAN DOES MAGIC TRICK, PULLS WOMAN'S BATHING SUIT OFF",
    id: 304,
  },
  {
    prompt: 'FLORIDA MAN CALLED 911 BECAUSE CHECKERS GOT ORDER WRONG',
    id: 305,
  },
  {
    prompt: 'FLORIDA MAN GETS 10 DAYS IN JAIL FOR PUNCHING SWAN',
    id: 306,
  },
  {
    prompt: 'FLORIDA MAN HAD 84 BAGS OF THC-LACED GUMMY CANDY IN CAR',
    id: 307,
  },
  {
    prompt: 'FLORIDA MAN BRAGS ABOUT ROBBERY ON FACEBOOK, GETS ARRESTED',
    id: 308,
  },
  {
    prompt: 'FLORIDA MAN GETS HOUSE ARREST FOR POSSESSION OF HORSEMEAT',
    id: 309,
  },
  {
    prompt: 'FLORIDA MAN STEALS DUMP TRUCK - SHOOTS AT HELICOPTER IN PURSUIT',
    id: 310,
  },
  {
    prompt: "FLORIDA MAN STEALS DECEASED VET'S WALLET TO BUY PIZZA",
    id: 311,
  },
  {
    prompt:
      "69-YEAR-OLD FLORIDA MAN RIDDLES WOMAN'S HOME WITH BULLETS AFTER SHE REFUSES TO HAVE SEX WITH HIM",
    id: 312,
  },
  {
    prompt: "FLORIDA MAN BUSTS CHURCH WINDOWS, SAYS HE WAS 'ANGRY WITH GOD'",
    id: 313,
  },
  {
    prompt: 'FLORIDA WOMAN BLAMES SWERVING ON SUNGLASSES, DOG',
    id: 314,
  },
  {
    prompt: 'FLORIDA WOMAN SHOOTS NAKED, POOP-COVERED INTRUDER',
    id: 315,
  },
  {
    prompt: 'FLORIDA MAN SET OFF SPRINKLERS, SOAKED HOTEL, COPS SAY',
    id: 316,
  },
  {
    prompt:
      'SHIRTLESS FLORIDA MAN SMASHES CAR WINDOW WITH BASEBALL BAT IN FIT OF ROAD RAGE',
    id: 317,
  },
  {
    prompt: 'FLORIDA MAN PISTOL WHIPS, SHOOTS AT MAN... OVER YAMS',
    id: 318,
  },
  {
    prompt:
      'FLORIDA MAN BUSTS THROUGH HAY BALES, CATCHES AIRTIME IN HIGH-SPEED CHASE',
    id: 319,
  },
  {
    prompt: 'FLORIDA MAN STEALS LOTTO TICKETS, RETURNS TO CASH THEM',
    id: 320,
  },
  {
    prompt: 'FLORIDA MAN FOUND WITH MOBILE METH LAB IN WALMART PARKING LOT',
    id: 321,
  },
  {
    prompt: 'FLORIDA MEN STEAL $16 IN CHICKEN, FACE $1000 BONDS',
    id: 322,
  },
  {
    prompt: "FLORIDA MAN WAKES UP NAKED IN STRANGER'S HOME",
    id: 323,
  },
  {
    prompt: 'OFFICIALS: FLORIDA MAN LETS KIDS PET HIS ALLIGATOR ON LEASH',
    id: 324,
  },
  {
    prompt: "FLORIDA MAN PLAYS NAKED GAME OF 'DING DONG DITCH'",
    id: 325,
  },
  {
    prompt:
      'FLORIDA MAN CALLS 911 OVER 100 TIMES, BLAMES "ARTISTIC ROBOTIC TECHNICIAN"',
    id: 326,
  },
  {
    prompt:
      'FLORIDA MAN MASSEUR CLAIMS SEXUAL ASSAULT WAS JUST HIS OIL BOTTLE, NOT HIS PENIS',
    id: 327,
  },
  {
    prompt: 'POLICE CALLED AFTER FLORIDA MAN DANCES NAKED IN THE RAIN',
    id: 328,
  },
  {
    prompt:
      "FLORIDA MAN ACCUSED OF MASTURBATING, EXPOSING SELF TO WOMAN: 'IT'S A NICE VIEW'",
    id: 329,
  },
  {
    prompt: 'FLORIDA MAN CALLS 911 AFTER GIRLFRIEND REFUSES TO BUY HIM VODKA',
    id: 330,
  },
  {
    prompt:
      'FLORIDA MAN FLASHES $100 BILLS, PEES ON HIMSELF AFTER REFUSING TO PAY FOR DRINKS HE ORDERED',
    id: 331,
  },
  {
    prompt: 'FLORIDA MAN ARRESTED FOR ALLEGED KALE HEIST AT WALMART',
    id: 332,
  },
  {
    prompt:
      "FLORIDA WOMAN 'PLAYS MERMAID' AND ENTERED HOMES WITHOUT PERMISSION",
    id: 333,
  },
  {
    prompt: 'BURYING YOUR TROUBLES, THE FLORIDA WAY: FLORIDA MAN BURIES BOSS',
    id: 334,
  },
  {
    prompt:
      "FLORIDA MAN WHO THREW ALLIGATOR INTO WENDY'S DRIVE-THRU WINDOW SENTENCED",
    id: 335,
  },
  {
    prompt: 'MACHETE WIELDING FLORIDA MAN ARRESTED ON DRUG, WEAPONS CHARGES',
    id: 336,
  },
  {
    prompt: 'FLORIDA MAN JUMPS FROM OVERPASS IN ATTEMPT TO ELUDE COPS',
    id: 337,
  },
  {
    prompt:
      'FLORID MAN TASED, ARRESTED AFTER JUMPING ON HOOD OF CAR ON PALMETTO EXPRESSWAY WITH KNIFE',
    id: 338,
  },
  {
    prompt:
      'FLORIDA MAN CREDIT CARD FRAUD INVESTIGATOR ARRESTED FOR CREDIT CARD FRAUD',
    id: 339,
  },
  {
    prompt: 'POLICE: FLORIDA MAN THROWS HOT PIZZA AT WIFE, CHILD',
    id: 340,
  },
  {
    prompt: "FLORIDA WOMAN STEALS PIZZA DELIVERY MAN'S CAR, CRASHES INTO HOUSE",
    id: 341,
  },
  {
    prompt: 'FLOIRIDA WOMAN SHOPLIFTER IDENTIFIED BY LEFT BEHIND CAR TAGS',
    id: 342,
  },
  {
    prompt: "FLORIDA MAN BURSTS INTO EX'S DELIVERY ROOM, FIGHTS HER BOYFRIEND",
    id: 343,
  },
  {
    prompt: 'FLORIDA MAN RUNS OVER ENDANGERED SANDHILL CRANE WITH GOLF CART',
    id: 344,
  },
  {
    prompt:
      'REPORT: DRUNKEN FLORIDA MAN DESTROYS POOL TABLE, THROWS BALL AT GUITAR',
    id: 345,
  },
  {
    prompt: 'KEY WEST LOOKING FOR OWNER OF ILLEGALLY PARKED FLINTSTONES CAR',
    id: 346,
  },
  {
    prompt: 'FLORIDA MAN FINED $48K FOR USING PHONE JAMMER ON THE ROAD',
    id: 347,
  },
  {
    prompt:
      "FLORIDA MAN ON 'TOP SECRET MISSION', BREAKS INTO STORE TO STEAL ENERGY DRINK AND A HONEY BUN",
    id: 348,
  },
  {
    prompt:
      'FLORIDA MAN CLIMBS THROUGH DRIVE-THRU WINDOW TO STEAL BURGER KING CASH REGISTER',
    id: 349,
  },
  {
    prompt:
      'SORE LOSER FLORIDA MAN TAKES SLEDGEHAMMER TO GAME AT ST. PETERSBURG CONVENIENCE STORE',
    id: 350,
  },
  {
    prompt: 'FLORIDA MAN LOCKED OUT OF HOTEL ROOM SHOOTS LOCK',
    id: 351,
  },
  {
    prompt:
      'FLORIDA MAN BURGLAR TRIES TO MAKE GETAWAY IN A GOLF CART, LANDS IN A POND',
    id: 352,
  },
  {
    prompt:
      'FLORIDA MAN POINTS LOADED SHOTGUN AT IRS WORKER WHO KNOCKED AT HIS DOOR',
    id: 353,
  },
  {
    prompt: "NAKED FLORIDA MAN SENDS HIS FIVE DOGS TO KILL 'MUSLIM TERRORIST'",
    id: 354,
  },
  {
    prompt: "NAKED FLORIDA MAN JUMPS AIRPORT FENCE TO 'GO BACK TO CUBA'",
    id: 355,
  },
  {
    prompt: 'FLORIDA MAN CALLS 911 ON HIMSELF',
    id: 356,
  },
  {
    prompt: 'FLORIDA MAN TO COP: "WHAT ARE YOU GONNA DO, FAT BOY?"',
    id: 357,
  },
  {
    prompt: 'ALLIGATOR BITES OFF ARM OF FLORIDA MAN TRYING TO FLEE THE COPS',
    id: 358,
  },
  {
    prompt: 'FLORIDA MAN ACCUSED OF LIGHTING SHIRT ON FIRE IN FRONT OF DMV',
    id: 359,
  },
  {
    prompt: 'POLICE: FLORIDA MAN CHARGED WITH STEALING $1 IN ROBBERY',
    id: 360,
  },
  {
    prompt: "FLORIDA MAN SHOOTS SELF, DOESN'T NOTICE FOR 3 DAYS",
    id: 361,
  },
  {
    prompt:
      "DEPUTIES:FLORIDA MAN KNOWN AS 'MURDER' CHARGED IN FATAL HOME INVASION",
    id: 362,
  },
  {
    prompt: 'FLORIDA MAN PULLED OVER WITH ALLIGATOR FOOT IN DASHBOARD',
    id: 363,
  },
  {
    prompt:
      'FLORIDA MAN ACCIDENTALLY SHOOTS HIMSELF DURING JOB INTERVIEW AT ELEMENTARY SCHOOL',
    id: 364,
  },
  {
    prompt: 'FLORIDA MAN KILLS BROTHER OVER CHEESEBURGER',
    id: 365,
  },
  {
    prompt:
      'POLICE: FLORIDA MAN TELLS WOMAN HE LOVES HER, MASTURBATES OUTSIDE HER WINDOW',
    id: 366,
  },
  {
    prompt: 'FLORIDA MAN STEALS SHIRTS, SHOES FOR JOB INTERVIEW',
    id: 367,
  },
  {
    prompt: 'FLORIDA MAN STUFFS PYTHON IN PANTS AT PET STORE',
    id: 368,
  },
  {
    prompt: 'FLORIDA MAN WITH KIDS IN CAR HAD .604 BLOOD ALCOHOL LEVEL',
    id: 369,
  },
  {
    prompt: "FLORIDA MAN TELLS POLICE THAT HIS NAME IS F*CK YOU'",
    id: 370,
  },
  {
    prompt: 'FLORIDA MAN BELLY DANCES IN A BIKINI FOR DRIVERS',
    id: 371,
  },
  {
    prompt: 'FLORIDA MAN BRINGS SWORD TO GUN FIGHT',
    id: 372,
  },
  {
    prompt: 'FLORIDA MAN TRIES TO SWIM AWAY FROM POLICE AFTER EXPOSING HIMSELF',
    id: 373,
  },
  {
    prompt: 'FLORIDA MAN CLINGS TO CAR IN ROAD RAGE INCIDENT',
    id: 374,
  },
  {
    prompt:
      "FLORIDA MAN EATS CRACK COCAINE; TELLS POLICE IT'S JOLLY RANCHER CANDY",
    id: 375,
  },
  {
    prompt: 'POLICE: FLORIDA MAN CONFRONTS OFFICERS WITH VIKING-STYLE AX',
    id: 376,
  },
  {
    prompt: 'FLORIDA MAN  HAS SEX IN COMMUNITY POOL, ATTACKS ONLOOKERS',
    id: 377,
  },
  {
    prompt: 'FLORIDA MAN DEFENDS SMALL CHIHUAHUA WITH LARGE MACHETE',
    id: 378,
  },
  {
    prompt:
      'HALF-BEARDED FLORIDA MAN SPENDS 4/20 IN JAIL FOR SELLING MARIJUANA THE NIGHT BEFORE',
    id: 379,
  },
  {
    prompt:
      'FLORIDA MAN ACCUSED OF SNATCHING HAT AND CALLING STEPSON A GOAT-ABUSING TERRORIST',
    id: 380,
  },
  {
    prompt:
      'FLORIDA MAN IMPERSONATED COP, USED SIRENS TO RUSH THROUGH TRAFFIC, SAY DEPUTIES',
    id: 381,
  },
  {
    prompt: 'FLORIDA MAN SUES FOR RIGHT TO MARRY HIS LAPTOP',
    id: 382,
  },
  {
    prompt: 'FLORIDA MAN HUMPS STOP SIGN WHILE STALKING EX',
    id: 383,
  },
  {
    prompt: "FLORIDA MAN EATS METH TO AVOID ARREST, DOESN'T WORK",
    id: 384,
  },
  {
    prompt:
      'FLORIDA MAN IS BUSTED WITH $100K WORTH OF STOLEN GOODS, HIDES DRUGS UP BUTT',
    id: 385,
  },
  {
    prompt:
      'FLORIDA MAN SAYS TOO MUCH MUSIC, MASTURBATION CAUSED HIM TO VANDALIZE HOME',
    id: 386,
  },
  {
    prompt: 'FLORIDA MAN TRIES TO KISS COTTONMOUTH SNAKE',
    id: 387,
  },
  {
    prompt:
      'FLORIDA MAN ARRESTED FOR SERIAL GROPINGS ON YOUTUBE: "IF YOU DON\'T TOUCH ASS YOU\'RE CRAZY"',
    id: 388,
  },
  {
    prompt: 'FLORIDA MAN ASKS COP TO JUMP START STOLEN TRUCK',
    id: 389,
  },
  {
    prompt: 'FLORIDA MAN TRIES TO ESCAPE COPS ON HIS HOVERBOARD, FAILS',
    id: 390,
  },
  {
    prompt: 'FLORIDA MAN TRIES TO BUY $60000 BMW WITH FOOD STAMPS',
    id: 391,
  },
  {
    prompt: 'FLORIDA MAN HAD HANDCUFF KEY IN HIS BUTT DURING HIGH SPEED CHASE',
    id: 392,
  },
  {
    prompt: 'FLORIDA MAN TAKES FIRE EXTINGUISHER OFF HOTEL WALL, SPRAYS PEOPLE',
    id: 393,
  },
  {
    prompt: 'FLORIDA MAN HIDES 15 STICKS OF STOLEN DEODORANT IN HIS PANTS',
    id: 394,
  },
  {
    prompt:
      'FLORIDA MAN ORDERS PIT BULL TO ATTACK COPS, ATTACKS FLORIDA MAN INSTEAD',
    id: 395,
  },
  {
    prompt: "FLORIDA MAN CAN'T GET CAR HE WANTS TO STEAL TO START",
    id: 396,
  },
  {
    prompt: "9.5-FOOT-LONG GATOR CAPTURED OUTSIDE OF FLORIDA MAN'S DOOR",
    id: 397,
  },
  {
    prompt: 'FLORIDA MAN SHOOTS AT NEIGHBOURS OVER FEEDING STRAY CATS',
    id: 398,
  },
  {
    prompt: 'FLORIDA MAN BRINGS MACHETE TO FIST FIGHT',
    id: 399,
  },
  {
    prompt: 'FLORIDA MAN HOLDING "DEATH TO AMERICA" SIGN BEAT UP BY AMERICANS',
    id: 400,
  },
  {
    prompt:
      'FLORIDA WOMAN CALLS 911 BECAUSE HER BACON PIZZA HAD HAMBURGER INSTEAD',
    id: 401,
  },
  {
    prompt: 'FLORIDA MAN URINATES ON TABLE, EXPOSES SELF IN CHURCH',
    id: 402,
  },
  {
    prompt: 'STOLEN PHONE RINGS IN POCKET OF SUSPECTED FLORIDA MAN',
    id: 403,
  },
  {
    prompt: 'FLORIDA MAN DRIVES SIX MILES WITH WIFE ATOP CAR',
    id: 404,
  },
  {
    prompt:
      "FLORIDA MAN CLAIMS TO BE WILLIAM SHATNER'S SON, SUES FOR $170 MILLION",
    id: 405,
  },
  {
    prompt: "FLORIDA MAN ATTACKS HIS MOM'S DOOR WITH A PITCHFORK",
    id: 406,
  },
  {
    prompt:
      'FLORIDA MAN JAILED AFTER REPORTING FOR JURY DUTY DRUNK, SUPREME COURT REVERSES',
    id: 407,
  },
  {
    prompt: 'FLORIDA MAN GRABS POLICE TASER AFTER BEING TASED FIVE TIMES',
    id: 408,
  },
  {
    prompt:
      'FLORIDA MAN ACCUSED OF STEALING WALLETS LEAVES HIS OWN AT THE SCENE',
    id: 409,
  },
  {
    prompt: 'FLORIDA MAN POINTS SPEAR GUN AT BOATERS IN KEYS, COPS SAY',
    id: 410,
  },
  {
    prompt: 'FLORIDA MAN THROWS GATOR INTO RESTAURANT',
    id: 411,
  },
  {
    prompt:
      'FLORIDA MAN REPORTS DEAD BODY BY TAKING SKULL TO PUBLIX, USING IT AS A HAND PUPPET',
    id: 412,
  },
];
